server:
  port: 8888


spring:
  application:
    name: config-server
  profiles: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chernyakVlad/fitness-app-microservices/
          search-paths: "config-properties/{application}/{profile}"
